### ISSUE TITLE
Docs and / or example to show hkCustom hint 

### ISSUE THREAD

**Issue by jmetz** [SolitudeSF/notify#1]
Any chance you could provide an example and/or docs on using the hkCustom hint? 
Been trying to create one and can't seem to figure out how!

**Comment by SolitudeSF** [comment]
`https://people.gnome.org/~mccann/docs/notification-spec/notification-spec-latest.html#hints` you have to construct your own DbusValue value which is part of https://github.com/zielmicha/nim-dbus, and your notification daemon must be able to do something with it.

```nim
import dbus

let hint = Hint(kind: hkCustom, customName: "name", customValue: 1.asDbusValue)
```
https://github.com/zielmicha/nim-dbus/blob/master/tests/tbasic.nim

basically, you're gonna have to touch dbus insides a bit.

**Comment by jmetz** [comment]
Many thanks for the clarification! I'll put together a simple example and submit a PR in case you want to add it.

**Comment by SolitudeSF** [comment]
> Many thanks for the clarification! I'll put together a simple example and submit a PR in case you want to add it.

great, because i most certainly didnt test the custom hint codepath.
